// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9izJZOGUxE6ZHGHhF3QZBUb_wIdRmj1A',
    appId: '1:209710918355:web:160f6c3e38fc7d64830226',
    messagingSenderId: '209710918355',
    projectId: 'cinebox-1103',
    authDomain: 'cinebox-1103.firebaseapp.com',
    storageBucket: 'cinebox-1103.firebasestorage.app',
    measurementId: 'G-M2WTTHSN86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAacqfwnzZ3ZCpRKYUlR09VXem2F_WpWtQ',
    appId: '1:209710918355:android:71de3557e6759110830226',
    messagingSenderId: '209710918355',
    projectId: 'cinebox-1103',
    storageBucket: 'cinebox-1103.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNwcFqyozKLO7LXhD7M527Lx7C3IZvnME',
    appId: '1:209710918355:ios:0e3071cc0cb2cb0b830226',
    messagingSenderId: '209710918355',
    projectId: 'cinebox-1103',
    storageBucket: 'cinebox-1103.firebasestorage.app',
    iosBundleId: 'com.example.cinebox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNwcFqyozKLO7LXhD7M527Lx7C3IZvnME',
    appId: '1:209710918355:ios:0e3071cc0cb2cb0b830226',
    messagingSenderId: '209710918355',
    projectId: 'cinebox-1103',
    storageBucket: 'cinebox-1103.firebasestorage.app',
    iosBundleId: 'com.example.cinebox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9izJZOGUxE6ZHGHhF3QZBUb_wIdRmj1A',
    appId: '1:209710918355:web:639165752db09f4d830226',
    messagingSenderId: '209710918355',
    projectId: 'cinebox-1103',
    authDomain: 'cinebox-1103.firebaseapp.com',
    storageBucket: 'cinebox-1103.firebasestorage.app',
    measurementId: 'G-GL5NZJVFRN',
  );
}
